# Generated by Django 4.1.3 on 2022-12-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lohithapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='pics')),
                ('detail', models.TextField()),
            ],
        ),
    ]
